name: har-api-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3
  - pip:
    - fastapi
    - uvicorn
    - python-multipart
    - openai
    - python-dotenv
    - pydantic
    - starlette
    - httpx